name: sunspot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.1.0  

  cupertino_icons: ^1.0.6

  maplibre_gl: ^0.25.0
  solar_calculator: ^1.0.3
  geolocator: ^13.0.1
  pointer_interceptor: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

    